URL_SERVICE = "https://cnt-1b741184-16f1-44b4-8846-d15ba74009f7.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREACION_DE_KIT = "/api/v1/kits"