URL_SERVICE = "https://cnt-68bff1b4-e482-4d73-9670-1839dc2deeac.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREACION_DE_KIT = "/api/v1/kits"